CREATE DATABASE IF NOT EXISTS booqueenDB;
USE booqueenDB;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    phoneNumber VARCHAR(20) NOT NULL,
    postalCode VARCHAR(10) NOT NULL,
    role VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS catalogueDirector (
    name VARCHAR(40) PRIMARY KEY,
    fileNameImages VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS catalogue (
    prix FLOAT,
    pays VARCHAR(255),
    ville VARCHAR(255) PRIMARY KEY,
    accroche VARCHAR(255),
    racineImg1 VARCHAR(255),
    racineImg2 VARCHAR(255),
    textVille1 VARCHAR(350),
    textVille2 VARCHAR(350),
    textVille3 VARCHAR(400),
    director_name VARCHAR(255),
    FOREIGN KEY (director_name) REFERENCES catalogueDirector(name)
);

CREATE TABLE IF NOT EXISTS reservations (
    username VARCHAR(70),
    ville VARCHAR(70),
    pays VARCHAR(70),
    prix FLOAT,
    FOREIGN KEY (username) REFERENCES users(username),
    FOREIGN KEY (ville) REFERENCES catalogue(ville)
);


INSERT INTO catalogueDirector (name, fileNameImages) VALUES
("France", "images/France/paysFrance.jpg"),
("Maroc", "images/Maroc/paysMaroc.jpg"),
("Italie", "images/Italie/paysItalie.jpg"),
("Croatie", "images/Croatie/paysCroatie.jpg"),
("Thaïlande", "images/Thaïlande/paysThailande.jpg"),
("États-Unis", "images/États-Unis/paysUS.jpg"),
("Grèce", "images/Grèce/paysGrece.jpg"),
("Mexique", "images/Mexique/paysMexique.jpg"),
("Japon", "images/Japon/paysJapon.jpg"),
("Nouvelle-Zélande", "images/Nouvelle-Zélande/paysNZ.jpg"),
("Islande", "images/Islande/paysIslande.jpg"),
("Système-Solaire", "images/Système-Solaire/paysSS.jpg");


insert into catalogue(prix, pays, ville, accroche, racineImg1, racineImg2, textVille1, textVille2, textVille3) values
(150.00, "France", "Paris", "Voyagez vers la capitale", "images/France/paris1.jpg", "images/France/paris2.jpg", "Bienvenue dans la ville lumière, la capitale de la mode, de la culture et du romantisme - Paris. Chez Booqueen, nous vous invitons à plonger dans l'essence même de cette métropole exceptionnelle, où l'histoire rencontre la modernité et l'élégance se mêle à la passion .", "Paris, la ville lumière, vous attend avec ses rues pavées, ses monuments emblématiques et son ambiance romantique. Des Champs-Élysées à la Tour Eiffel, chaque coin de Paris respire l'histoire et l'élégance. Découvrez les musées renommés tels que le Louvre, dégustez une délicieuse pâtisserie dans une charmante brasserie parisienne.", "Chez Booqueen, nous comprenons l'importance de chaque voyage. C'est pourquoi nous mettons tout en œuvre pour rendre votre expérience de réservation aussi agréable que votre séjour à Paris. Notre équipe dévouée vous garantit des vols confortables, des tarifs compétitifs et un service personnalisé tout au long de votre voyage."),
(120.00, "France", "Lyon", "Découvrez la ville des lumières", "images/France/lyon1.jpg", "images/France/lyon2.jpg", "Bienvenue dans la ville des lumières, Lyon, réputée pour sa gastronomie, son architecture unique et son ambiance chaleureuse. Chez Booqueen, nous vous invitons à explorer les ruelles de cette ville pleine de charme, où la tradition se mêle à l'innovation.", "Lyon, la ville des lumières, vous offre des expériences uniques, des traboules mystérieuses aux délicieux bouchons lyonnais. Des quais de la Saône à la colline de Fourvière, découvrez une cité riche en histoire et en saveurs.", "Chez Booqueen, nous comprenons l'importance de chaque voyage. C'est pourquoi nous mettons tout en œuvre pour rendre votre expérience de réservation aussi agréable que votre séjour à Lyon. Notre équipe dévouée vous garantit des vols confortables, des tarifs compétitifs et un service personnalisé tout au long de votre voyage."),
(130.00, "France", "Marseille", "Explorez la cité phocéenne", "images/France/marseille1.jpg", "images/France/marseille2.jpg", "Bienvenue à Marseille, la perle de la Méditerranée, où l'histoire ancienne se marie harmonieusement avec la vie moderne. Chez Booqueen, nous vous invitons à plonger dans l'effervescence de cette ville portuaire, baignée de lumière et d'une énergie méditerranéenne incomparable.", "Marseille, avec ses marchés animés, ses ruelles pittoresques du Vieux-Port et ses vues spectaculaires depuis la basilique Notre-Dame de la Garde, vous offre une expérience unique. Découvrez une gastronomie méditerranéenne délicieuse, explorez les calanques préservées et laissez-vous séduire par la convivialité chaleureuse des habitants.", "Chez Booqueen, nous comprenons l'importance de chaque voyage. C'est pourquoi nous mettons tout en œuvre pour rendre votre expérience de réservation aussi agréable que votre séjour à Marseille. Notre équipe dévouée vous garantit des vols confortables, des tarifs compétitifs et un service personnalisé tout au long de votre voyage."),
(140.00, "France", "Strasbourg", "Découvrez la capitale européenne", "images/France/strasbourg1.jpg", "images/France/strasbourg2.jpg", "Bienvenue à Strasbourg, où l'histoire et la culture alsaciennes prennent vie au cœur de l'Europe. Chez Booqueen, nous vous invitons à vous immerger dans la richesse de cette ville, où les façades à colombages, les canaux pittoresques et l'esprit festif créent une ambiance unique.", "Strasbourg, avec sa cathédrale emblématique, ses marchés de Noël enchantés et ses institutions européennes, offre une expérience culturelle incomparable. Explorez les quartiers authentiques, dégustez les spécialités alsaciennes dans les winstubs traditionnelles et laissez-vous émerveiller par la beauté de cette ville dynamique.", "Chez Booqueen, nous célébrons avec enthousiasme la riche diversité des destinations qui composent notre carte aérienne. Nous mettons à votre disposition une expérience de voyage inégalée, alliant le confort supérieur de nos vols, des tarifs compétitifs qui s'adaptent à toutes les bourses, et un service personnalisé pour un séjour mémorable."),
(130.00, "Maroc", "Agadir", "Découvrez la perle du sud", "images/Maroc/agadir1.jpg", "images/Maroc/agadir2.jpg", "Bienvenue à Agadir, la perle du sud du Maroc, où le soleil, les plages de sable fin et la culture berbère créent une harmonie envoûtante. Chez Booqueen, plongez dans la douceur de vivre de cette station balnéaire exceptionnelle, alliant détente et découverte.", "Agadir, avec son littoral spectaculaire, ses marchés animés et ses jardins luxuriants, vous invite à une expérience balnéaire authentique. Explorez la médina, savourez la cuisine marocaine dans les souks, et laissez-vous emporter par la chaleur de l'hospitalité marocaine.", "Chez Booqueen, nous comprenons l'importance de chaque voyage. C'est pourquoi nous mettons tout en œuvre pour rendre votre expérience de réservation aussi agréable que votre séjour à Agadir. Notre équipe dévouée vous garantit des vols confortables, des tarifs compétitifs et un service personnalisé tout au long de votre voyage."),
(120.00, "Maroc", "Rabat", "Explorez la capitale du Maroc", "images/Maroc/rabat1.jpg", "images/Maroc/rabat2.jpg", "Bienvenue à Rabat, la capitale du Maroc, où l'histoire, la modernité et la culture se rencontrent avec élégance. Chez Booqueen, découvrez l'effervescence de cette ville aux rues animées, aux jardins luxuriants et aux monuments emblématiques.", "Rabat, avec sa médina préservée, ses palais royaux et sa proximité avec l'océan Atlantique, offre une expérience marocaine authentique. Explorez la kasbah des Oudaias, déambulez dans les souks colorés et savourez la cuisine locale riche en saveurs.", "Chez Booqueen, nous célébrons la diversité des destinations. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé pour rendre votre séjour à Rabat mémorable."),
(140.00, "Maroc", "Marrakech", "Plongez dans la cité rouge", "images/Maroc/marrakech1.jpg", "images/Maroc/marrakech2.jpg", "Bienvenue à Marrakech, la cité rouge du Maroc, où les traditions millénaires se mêlent à l'effervescence urbaine. Chez Booqueen, plongez dans l'atmosphère enchanteresse de cette ville impériale, entre souks animés, palais somptueux et jardins luxuriants.", "Marrakech, avec sa médina classée à l'UNESCO, sa place Jemaa el-Fna vibrante et ses riads traditionnels, offre une expérience sensorielle unique. Découvrez l'art de la négociation dans les souks, dégustez la cuisine locale épicée et ressentez la magie de la place animée.", "Chez Booqueen, nous mettons tout en œuvre pour rendre votre expérience de réservation aussi agréable que votre séjour à Marrakech. Notre équipe dévouée vous garantit des vols confortables, des tarifs compétitifs et un service personnalisé tout au long de votre voyage."),
(130.00, "Maroc", "Tanger", "Explorez la porte du Maroc", "images/Maroc/tanger1.jpg", "images/Maroc/tanger2.jpg", "Bienvenue à Tanger, la porte du Maroc, où l'histoire, la mer Méditerranée et la culture se rencontrent dans une harmonie envoûtante. Chez Booqueen, découvrez la beauté de cette ville côtière, entre médina animée, plages dorées et falaises majestueuses.", "Tanger, avec son mélange unique d'influences arabes, africaines et européennes, offre une expérience marocaine distinctive. Explorez la kasbah, déambulez dans les souks, et admirez la vue panoramique depuis le cap Spartel. Laissez-vous séduire par l'atmosphère cosmopolite de cette ville emblématique.", "Chez Booqueen, nous célébrons avec enthousiasme la riche diversité des destinations qui composent notre carte aérienne. Nous mettons à votre disposition une expérience de voyage inégalée, alliant le confort supérieur de nos vols, des tarifs compétitifs qui s'adaptent à toutes les bourses, et un service personnalisé pour un séjour mémorable."),
(160.00, "Italie", "Rome", "Découvrez la Ville Éternelle", "images/Italie/rome1.jpg", "images/Italie/rome2.jpg", "Bienvenue à Rome, la Ville Éternelle, où l'histoire ancienne, l'art et la culture vous transportent à travers les siècles. Chez Booqueen, plongez dans l'atmosphère unique de la capitale italienne, entre le Colisée imposant, le Forum romain et les ruelles pittoresques.", "Rome, avec ses célèbres fontaines, ses églises majestueuses et ses places animées, offre une expérience italienne incomparable. Explorez le Vatican, dégustez une délicieuse cuisine italienne et laissez-vous inspirer par l'art et l'architecture exceptionnels de la ville.", "Chez Booqueen, nous célébrons avec enthousiasme la riche diversité des destinations qui composent notre carte aérienne. Nous mettons à votre disposition une expérience de voyage inégalée, alliant le confort supérieur de nos vols, des tarifs compétitifs qui s'adaptent à toutes les bourses, et un service personnalisé pour un séjour mémorable."),
(180.00, "Italie", "Venise", "Explorez la Cité des Canaux", "images/Italie/venise1.jpg", "images/Italie/venise2.jpg", "Bienvenue à Venise, la Cité des Canaux, où la romance flotte dans l'air à chaque coin de rue. Chez Booqueen, découvrez l'élégance intemporelle de cette ville lacustre, entre les canaux sinueux, les palais vénitiens et les places emblématiques.", "Venise, avec ses gondoles pittoresques, ses masques vénitiens et son histoire fascinante, offre une expérience unique en son genre. Traversez le Pont du Rialto, visitez la Place Saint-Marc et dégustez des spécialités italiennes dans les trattorias traditionnelles.", "Chez Booqueen, nous mettons tout en œuvre pour rendre votre expérience de réservation aussi agréable que votre séjour à Venise. Notre équipe dévouée vous garantit des vols confortables, des tarifs compétitifs et un service personnalisé tout au long de votre voyage."),
(150.00, "Italie", "Pompéi", "Voyagez dans le Temps", "images/Italie/pompei1.jpg", "images/Italie/pompei2.jpg", "Bienvenue à Pompéi, où les vestiges de l'Antiquité romaine prennent vie. Chez Booqueen, explorez cette ville figée dans le temps, entre les ruines fascinantes, les fresques préservées et l'histoire captivante du mont Vésuve.", "Pompéi, avec son amphithéâtre bien conservé, ses thermes anciens et ses rues pavées, offre une plongée unique dans le passé. Marchez sur les traces des anciens Romains, découvrez les mystères de la cité ensevelie et revivez l'éclat de cette ville antique.", "Chez Booqueen, nous comprenons l'importance de chaque voyage. C'est pourquoi nous mettons tout en œuvre pour rendre votre expérience de réservation aussi agréable que votre séjour à Pompéi. Notre équipe dévouée vous garantit des vols confortables, des tarifs compétitifs et un service personnalisé tout au long de votre voyage."),
(170.00, "Italie", "Florence", "Plongez dans la Renaissance", "images/Italie/florence1.jpg", "images/Italie/florence2.jpg", "Bienvenue à Florence, le berceau de la Renaissance, où l'art, la culture et l'architecture célèbrent l'esprit créatif. Chez Booqueen, plongez dans l'atmosphère artistique de cette ville toscane, entre les chefs-d'œuvre de la Galerie des Offices, le Ponte Vecchio et la majestueuse cathédrale.", "Florence, avec ses musées renommés, ses places élégantes et ses jardins pittoresques, offre une immersion totale dans l'ère de la Renaissance. Admirez les sculptures de Michel-Ange, déambulez dans les ruelles historiques et dégustez une cuisine toscane délicieuse.", "Chez Booqueen, nous mettons tout en œuvre pour rendre votre expérience de réservation aussi agréable que votre séjour à Florence. Notre équipe dévouée vous garantit des vols confortables, des tarifs compétitifs et un service personnalisé tout au long de votre voyage."),
(160.00, "Croatie", "Dubrovnik", "Explorez la Perle de l'Adriatique", "images/Croatie/dubrovnik1.jpg", "images/Croatie/dubrovnik2.jpg", "Bienvenue à Dubrovnik, la Perle de l'Adriatique, où les remparts médiévaux rencontrent les eaux azur de la mer Adriatique. Chez Booqueen, nous vous invitons à vous promener dans les rues bien préservées de ce site classé au patrimoine mondial de l'UNESCO, où l'histoire et la beauté s'entremêlent.", "Dubrovnik, avec ses remparts impressionnants et son centre historique, offre un mélange captivant de culture et de beauté naturelle. Explorez les ruelles de la vieille ville, profitez des plages pittoresques et découvrez la richesse culturelle de cette ville côtière.", "Chez Booqueen, nous comprenons l'importance de chaque voyage. C'est pourquoi nous mettons tout en œuvre pour rendre votre expérience de réservation aussi agréable que votre séjour à Dubrovnik. Notre équipe dévouée vous garantit des vols confortables, des tarifs compétitifs et un service personnalisé tout au long de votre voyage."),
(140.00, "Croatie", "Split", "Découvrez la Beauté Côtière", "images/Croatie/split1.jpg", "images/Croatie/split2.jpg", "Bienvenue à Split, une ville côtière où la mer et l'histoire se rencontrent. Chez Booqueen, nous vous invitons à explorer cette destination pittoresque, entre palais anciens, rues animées et vues magnifiques sur la mer Adriatique.", "Split, avec ses vestiges romains, son palais de Dioclétien et ses plages dorées, offre une expérience riche en découvertes. Promenez-vous dans la vieille ville, goûtez aux délices locaux et laissez-vous emporter par le charme de cette cité dalmate.", "Chez Booqueen, nous célébrons la diversité des destinations. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé pour rendre votre séjour à Split mémorable."),
(130.00, "Croatie", "Zagreb", "Explorez le Charme de la Capitale", "images/Croatie/zagreb1.jpg", "images/Croatie/zagreb2.jpg", "Bienvenue à Zagreb, la capitale de la Croatie, où la modernité se marie à l'histoire. Chez Booqueen, explorez cette ville dynamique, entre architecture remarquable, cafés animés et parcs pittoresques.", "Zagreb, avec ses places historiques, son marché animé et sa scène culturelle, offre une expérience variée. Découvrez les musées, visitez la cathédrale et profitez de la convivialité des habitants.", "Chez Booqueen, nous mettons tout en œuvre pour rendre votre expérience de réservation aussi agréable que votre séjour à Zagreb. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé."),
(180.00, "Thaïlande", "Bangkok", "Découvrez la Capitale Trépidante", "images/Thaïlande/bangkok1.jpg", "images/Thaïlande/bangkok2.jpg", "Bienvenue à Bangkok, la capitale trépidante de la Thaïlande, où l'ancien et le moderne se mêlent dans une symphonie vibrante. Chez Booqueen, nous vous invitons à explorer les temples scintillants, à déguster la cuisine de rue épicée et à plonger dans la culture effervescente de la ville.", "Bangkok, avec ses gratte-ciel étincelants et ses marchés animés, offre une expérience captivante. Des temples majestueux comme le Wat Arun aux quartiers modernes de Sukhumvit, chaque coin de la ville raconte une histoire unique. Découvrez la vie nocturne animée et les canaux tranquilles de la Venise de l'Est.", "Chez Booqueen, nous comprenons l'importance de chaque voyage. Nous vous garantissons des vols confortables, des tarifs compétitifs et un service personnalisé pour rendre votre séjour à Bangkok aussi enrichissant que la diversité de la ville elle-même."),
(160.00, "Thaïlande", "Chiang Mai", "Explorez la Perle du Nord", "images/Thaïlande/chiangmai1.jpg", "images/Thaïlande/chiangmai2.jpg", "Bienvenue à Chiang Mai, la perle du Nord de la Thaïlande, où la tradition rencontre la nature dans une harmonie parfaite. Booqueen vous invite à découvrir les temples anciens, à explorer la campagne luxuriante.", "Chiang Mai, entourée de montagnes majestueuses, offre une évasion paisible. Des marchés nocturnes colorés aux temples bouddhistes emblématiques tels que le Wat Phra Singh, chaque moment à Chiang Mai est imprégné de charme. Découvrez l'artisanat local.", "Chez Booqueen, nous nous engageons à rendre votre expérience de réservation aussi agréable que votre séjour à Chiang Mai. Profitez de vols confortables, de tarifs compétitifs."),
(140.00, "Thaïlande", "Ayutthaya", "Plongez dans l'Histoire Ancienne", "images/Thaïlande/ayutthaya1.jpg", "images/Thaïlande/ayutthaya2.jpg", "Bienvenue à Ayutthaya, une ancienne capitale de la Thaïlande, où les vestiges majestueux témoignent de la grandeur passée. Chez Booqueen, nous vous invitons à plonger dans l'histoire de cette ville, classée au patrimoine mondial de l'UNESCO.", "Ayutthaya, avec ses temples anciens et ses ruines bien préservées, offre une expérience immersive dans le passé. Explorez les temples fascinants tels que Wat Mahathat, promenez-vous à vélo et ressentez la magie de cette ancienne cité.", "Chez Booqueen, nous célébrons la richesse des destinations. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé pour rendre votre séjour à Ayutthaya mémorable."),
(200.00, "Thaïlande", "Phuket", "Détente et Aventure sur l'Île Paradisiaque", "images/Thaïlande/phuket1.jpg", "images/Thaïlande/phuket2.jpg", "Bienvenue à Phuket, une île paradisiaque où détente et aventure se rencontrent. Chez Booqueen, profitez des plages dorées, des sports nautiques et de la vie nocturne animée.", "Phuket, avec ses stations balnéaires luxueuses et ses activités variées, offre une escapade parfaite. Explorez la vieille ville de Phuket, savourez la cuisine thaïlandaise et détendez-vous sur les plages idylliques.", "Chez Booqueen, nous nous engageons à rendre votre expérience de réservation aussi agréable que votre séjour à Phuket. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé."),
(300.00, "États-Unis", "New York", "La Ville Qui Ne Dort Jamais", "images/États-Unis/newyork1.jpg", "images/États-Unis/newyork2.jpg", "Bienvenue à New York, la ville emblématique qui définit l'énergie urbaine et la diversité culturelle. Chez Booqueen, nous vous invitons à explorer les gratte-ciel majestueux, à flâner dans Central Park et à ressentir le pouls incessant de Times Square.", "New York, avec ses quartiers uniques, ses théâtres de Broadway et sa cuisine mondiale, offre une expérience inoubliable. Découvrez la Statue de la Liberté, parcourez les galeries d'art de Chelsea et vivez la magie de cette métropole dynamique.", "Chez Booqueen, nous nous engageons à rendre votre voyage à New York aussi passionnant que la ville elle-même. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé pour une immersion totale dans la Grosse Pomme."),
(400.00, "États-Unis", "Las Vegas", "L'Éclat des Lumières et des Casinos", "images/États-Unis/lasvegas1.jpg", "images/États-Unis/lasvegas2.jpg", "Bienvenue à Las Vegas, la capitale mondiale du divertissement, où les lumières éblouissantes, les spectacles grandioses et les casinos emblématiques créent une atmosphère unique. Chez Booqueen, plongez dans le glamour de la Strip, tentez votre chance dans les célèbres casinos et assistez à des spectacles sensationnels.", "Las Vegas, avec ses hôtels extravagants, ses piscines somptueuses et ses restaurants de renommée mondiale, offre une expérience excitante. Explorez le désert environnant, découvrez les spectacles de renommée mondiale et vivez une aventure sans pareille au cœur de l'Amérique du divertissement.", "Chez Booqueen, nous sommes déterminés à rendre votre séjour à Las Vegas aussi brillant que les néons du Strip. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé pour une expérience inoubliable dans la capitale mondiale du jeu."),
(350.00, "États-Unis", "Los Angeles", "La Cité des Anges et du Divertissement", "images/États-Unis/losangeles1.jpg", "images/États-Unis/losangeles2.jpg", "Bienvenue à Los Angeles, la Cité des Anges, où le glamour hollywoodien, les plages ensoleillées et la culture artistique se rencontrent. Chez Booqueen, découvrez la magie de Hollywood, détendez-vous sur les plages emblématiques et explorez les quartiers dynamiques de la ville.", "Los Angeles, avec ses studios de cinéma légendaires, ses parcs d'attractions renommés et sa scène artistique florissante, offre une expérience diversifiée. Visitez le Walk of Fame, parcourez les musées de renom, et plongez-vous dans la créativité qui définit cette métropole captivante.", "Chez Booqueen, nous nous engageons à rendre votre séjour à Los Angeles aussi captivant que le paysage varié de la ville. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé pour une exploration sans souci de la Cité des Anges."),
(250.00, "États-Unis", "Washington", "Capitale Politique et Culturelle", "images/États-Unis/washington1.jpg", "images/États-Unis/washington2.jpg", "Bienvenue à Washington, D.C., la capitale des États-Unis, où l'histoire politique, les monuments emblématiques et les musées exceptionnels créent une toile de fond impressionnante. Chez Booqueen, explorez le National Mall, visitez les musées Smithsonian et découvrez le cœur du pays.", "Washington, avec ses bâtiments gouvernementaux majestueux, ses quartiers historiques et ses événements culturels, offre une expérience enrichissante. Admirez la Maison Blanche, parcourez les mémoriaux dédiés aux grands leaders et plongez-vous dans la scène artistique florissante de la ville.", "Chez Booqueen, nous nous engageons à rendre votre visite à Washington aussi éducative que passionnante. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé pour une exploration immersive de la capitale politique et culturelle des États-Unis."),
(180.00, "Grèce", "Athènes", "Découvrez la cité antique", "images/Grèce/athenes1.jpg", "images/Grèce/athenes2.jpg", "Bienvenue à Athènes, berceau de la civilisation occidentale, où l'histoire antique rencontre la vie moderne. Chez Booqueen, plongez dans la richesse culturelle de cette cité pleine de temples majestueux et d'histoires mythologiques.", "Athènes, avec son Acropole emblématique et son Agora antique, vous transporte à une époque où la philosophie, l'art et la démocratie ont prospéré. Explorez les rues animées de Plaka, goûtez aux saveurs méditerranéennes et laissez-vous imprégner de la magie de cette ville fascinante.", "Chez Booqueen, nous vous offrons une expérience unique à Athènes. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé pour rendre votre voyage aussi mémorable que les vestiges de l'Antiquité."),
(160.00, "Grèce", "Corinthe", "Explorez l'histoire et la mer", "images/Grèce/corinthe1.jpg", "images/Grèce/corinthe2.jpg", "Bienvenue à Corinthe, une ville riche en histoire entre la mer et les montagnes. Chez Booqueen, explorez cette cité antique, entre le canal emblématique et les ruines romaines fascinantes.", "Corinthe, avec son patrimoine historique et sa beauté naturelle, offre une expérience authentique. Promenez-vous le long de ses rues anciennes, visitez le temple d'Apollon et profitez de la vue imprenable sur le golfe de Corinthe.", "Chez Booqueen, nous célébrons la diversité des destinations. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé pour rendre votre séjour à Corinthe mémorable."),
(200.00, "Grèce", "Cyclades", "Explorez les îles grecques envoûtantes", "images/Grèce/cyclades1.jpg", "images/Grèce/cyclades2.jpg", "Bienvenue dans les Cyclades, un archipel de beauté incomparable. Chez Booqueen, découvrez des îles blanches aux eaux bleues cristallines, entre villages pittoresques et plages idylliques.", "Les Cyclades, avec leurs maisons blanchies à la chaux, leurs ruelles sinueuses et leurs couchers de soleil spectaculaires, offrent une escapade inoubliable. Explorez Santorin, Mykonos et d'autres îles pour une expérience de rêve.", "Chez Booqueen, nous mettons tout en œuvre pour rendre votre expérience de réservation aussi agréable que votre séjour dans les Cyclades. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé."),
(220.00, "Grèce", "Santorin", "Vivez une expérience unique dans les îles grecques", "images/Grèce/santorin1.jpg", "images/Grèce/santorin2.jpg", "Bienvenue à Santorin, joyau des Cyclades, où les maisons blanchies à la chaux se perchent sur des falaises volcaniques avec une vue à couper le souffle. Chez Booqueen, plongez dans l'élégance et l'authenticité de cette île envoûtante.", "Santorin, avec ses panoramas à couper le souffle, ses eaux cristallines et ses couchers de soleil inoubliables, offre une expérience romantique. Explorez les villages pittoresques, dégustez une cuisine locale raffinée et laissez-vous emporter par la magie de Santorin.", "Chez Booqueen, nous vous offrons une expérience exceptionnelle à Santorin. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé pour rendre votre séjour aussi captivant que les panoramas spectaculaires de cette île grecque."),
(180.00, "Mexique", "Cancún", "Découvrez la perle des Caraïbes", "images/Mexique/cancun1.jpg", "images/Mexique/cancun2.jpg", "Bienvenue à Cancún, la perle des Caraïbes, où les plages de sable blanc rencontrent les eaux cristallines. Chez Booqueen, nous vous invitons à plonger dans la beauté tropicale de cette destination paradisiaque, où détente et aventures vous attendent.", "Cancún, avec ses complexes hôteliers luxueux, ses sites archéologiques mayas et sa vie nocturne animée, vous offre une expérience inoubliable. Explorez les récifs coralliens, détendez-vous sur les plages idylliques et laissez-vous emporter par l'atmosphère enchanteresse de cette ville balnéaire.", "Chez Booqueen, nous sommes ravis de vous accompagner dans cette aventure à Cancún. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé pour rendre votre séjour aussi exceptionnel que les couchers de soleil sur la mer des Caraïbes."),
(160.00, "Mexique", "Mexico", "Explorez la capitale vibrante", "images/Mexique/mexico1.jpg", "images/Mexique/mexico2.jpg", "Bienvenue à Mexico, une capitale vibrante où l'histoire, la culture et la modernité se rencontrent. Chez Booqueen, nous vous invitons à explorer les trésors de cette métropole fascinante, des pyramides anciennes aux quartiers animés.", "Mexico, avec ses musées exceptionnels, ses marchés colorés et sa scène artistique dynamique, vous offre une plongée dans la riche diversité mexicaine. Découvrez la cuisine savoureuse, admirez l'architecture coloniale et plongez dans l'effervescence de cette ville cosmopolite.", "Chez Booqueen, nous sommes fiers de vous offrir une expérience unique à Mexico. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé pour rendre votre séjour aussi captivant que les ruelles de la Zona Rosa."),
(140.00, "Mexique", "Campeche", "Plongez dans le charme colonial", "images/Mexique/campeche1.jpg", "images/Mexique/campeche2.jpg", "Bienvenue à Campeche, une ville au charme colonial préservé, où les façades colorées et les remparts racontent une histoire fascinante. Chez Booqueen, nous vous invitons à plonger dans l'atmosphère authentique de cette perle méconnue.", "Campeche, avec ses rues pavées, ses forts historiques et ses festivals animés, vous transporte dans le passé du Mexique. Explorez les marchés locaux, savourez la cuisine traditionnelle et laissez-vous séduire par l'accueil chaleureux des habitants.", "Chez Booqueen, nous sommes ravis de vous faire découvrir la beauté de Campeche. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé pour rendre votre séjour aussi authentique que les murs de la vieille ville."),
(150.00, "Mexique", "Valladolid", "Explorez le cœur de la péninsule", "images/Mexique/valladolid1.jpg", "images/Mexique/valladolid2.jpg", "Bienvenue à Valladolid, une ville charmante nichée au cœur de la péninsule du Yucatán. Chez Booqueen, nous vous invitons à découvrir l'histoire et la culture mexicaine tout en explorant les sites archéologiques voisins.", "Valladolid, avec ses rues pittoresques et ses marchés colorés, offre une expérience authentique. Découvrez les cénotes, goûtez à la cuisine locale et laissez-vous charmer par cette ville au patrimoine unique.", "Chez Booqueen, nous mettons tout en œuvre pour rendre votre expérience de réservation aussi agréable que votre séjour à Valladolid. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé."),
(160.00, "Japon", "Tokyo", "Découvrez la capitale vibrante", "images/Japon/tokyo1.jpg", "images/Japon/tokyo2.jpg", "Bienvenue à Tokyo, la capitale vibrante du Japon, où la modernité et la tradition se rencontrent. Chez Booqueen, plongez dans l'effervescence de cette métropole asiatique, où les gratte-ciel et les temples ancestraux coexistent harmonieusement.", "Tokyo, avec ses quartiers animés, ses marchés aux poissons et ses jardins tranquilles, offre une expérience unique. Découvrez la vie nocturne animée, les boutiques de mode et les délices culinaires dans cette ville captivante.", "Chez Booqueen, nous vous offrons des vols confortables, des tarifs compétitifs et un service personnalisé pour que votre séjour à Tokyo soit inoubliable."),
(170.00, "Japon", "Kyoto", "Explorez la beauté traditionnelle", "images/Japon/kyoto1.jpg", "images/Japon/kyoto2.jpg", "Bienvenue à Kyoto, la ville des temples, des jardins et des traditions anciennes. Chez Booqueen, plongez dans l'atmosphère paisible de cette ville japonaise, où l'histoire et la culture se mêlent.", "Kyoto, avec ses sanctuaires et ses temples historiques, vous offre une expérience authentique du Japon. Promenez-vous dans les rues de la vieille ville, explorez les jardins zen et découvrez l'artisanat local.", "Chez Booqueen, nous mettons tout en œuvre pour rendre votre expérience de réservation aussi agréable que votre séjour à Kyoto. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé."),
(180.00, "Japon", "Osaka", "Vivez l'effervescence urbaine", "images/Japon/osaka1.jpg", "images/Japon/osaka2.jpg", "Bienvenue à Osaka, la ville dynamique où la gastronomie exceptionnelle et le divertissement abondent. Chez Booqueen, plongez dans l'effervescence de cette métropole japonaise, où la modernité s'associe à une atmosphère conviviale.", "Osaka, avec son château imposant, ses quartiers commerçants animés et ses délices culinaires comme le takoyaki, offre une expérience unique. Découvrez le contraste entre les gratte-ciel illuminés et les sanctuaires traditionnels dans cette ville pleine de surprises.", "Chez Booqueen, nous vous proposons des vols vers Osaka pour que vous puissiez découvrir cette ville animée. Profitez de tarifs compétitifs, d'un service de qualité et plongez dans l'énergie vibrante d'Osaka lors de votre séjour inoubliable."),
(190.00, "Japon", "Karuizawa", "Échappez à la sérénité des montagnes", "images/Japon/karuizawa1.jpg", "images/Japon/karuizawa2.jpg", "Bienvenue à Karuizawa, une retraite paisible nichée dans les montagnes verdoyantes. Chez Booqueen, échappez à l'agitation urbaine et découvrez cette destination japonaise où la nature rencontre l'élégance décontractée.", "Karuizawa, avec ses onsens relaxants, ses sentiers de randonnée pittoresques et ses boutiques élégantes, offre une expérience unique loin du tumulte des grandes villes. Profitez d'une escapade relaxante dans cette destination prisée des Japonais.", "Chez Booqueen, nous vous invitons à découvrir Karuizawa. Profitez de nos vols pour cette destination apaisante, avec des tarifs compétitifs et un service attentif pour rendre votre séjour aussi relaxant que les sources chaudes de la région."),
(180.00, "Nouvelle-Zélande", "Mount Maunganui", "Découvrez la beauté côtière", "images/Nouvelle-Zélande/mount_maunganui1.jpg", "images/Nouvelle-Zélande/mount_maunganui2.jpg", "Bienvenue à Mount Maunganui, une station balnéaire réputée pour ses plages de sable blanc et ses activités de plein air. Chez Booqueen, nous vous invitons à explorer la beauté de cette destination côtière.", "Mount Maunganui offre des paysages époustouflants, des sentiers de randonnée pittoresques et une vue panoramique sur la baie. Profitez de sports nautiques, de promenades en bord de mer et de couchers de soleil spectaculaires.", "Chez Booqueen, nous célébrons la richesse des destinations. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé pour rendre votre séjour à Mount Maunganui mémorable."),
(170.00, "Nouvelle-Zélande", "Nelson", "Explorez la région des vins et de l'art", "images/Nouvelle-Zélande/nelson1.jpg", "images/Nouvelle-Zélande/nelson2.jpg", "Bienvenue à Nelson, une charmante ville nichée dans une région réputée pour ses vins et son art. Chez Booqueen, nous vous invitons à découvrir les délices culinaires, les paysages pittoresques et la culture artistique de Nelson.", "Nelson offre des vignobles réputés, des galeries d'art captivantes et une ambiance décontractée. Explorez les marchés locaux, les plages dorées et les montagnes majestueuses de la région.", "Chez Booqueen, nous comprenons l'importance de chaque voyage. C'est pourquoi nous mettons tout en œuvre pour rendre votre expérience de réservation aussi agréable que votre séjour à Nelson. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé."),
(200.00, "Islande", "Reykjavik", "Découvrez la capitale islandaise", "images/Islande/reykjavik1.jpg", "images/Islande/reykjavik2.jpg", "Bienvenue à Reykjavik, la capitale islandaise, où la nature rencontre la culture nordique moderne. Chez Booqueen, nous vous invitons à explorer cette ville dynamique située entre mer et montagnes, offrant une expérience unique.", "Reykjavik, avec son architecture moderne et ses bains géothermiques, est le point de départ idéal pour découvrir les merveilles naturelles de l'Islande. Des aurores boréales aux geysers, en passant par les cascades majestueuses, chaque coin de l'Islande raconte une histoire fascinante.", "Chez Booqueen, nous sommes fiers de vous offrir des vols vers l'Islande qui combinent confort, tarifs compétitifs et un service attentionné. Préparez-vous à vivre une aventure islandaise inoubliable."),
(180.00, "Islande", "Akureyri", "Explorez la perle du Nord", "images/Islande/akureyri1.jpg", "images/Islande/akureyri1.jpg", "Bienvenue à Akureyri, la perle du Nord, où les fjords majestueux rencontrent une atmosphère tranquille. Chez Booqueen, nous vous invitons à découvrir le charme de cette ville pittoresque, porte d'entrée vers les paysages époustouflants de l'Islande septentrionale.", "Akureyri, avec ses jardins botaniques, ses églises historiques et ses festivals animés, offre une expérience relaxante au cœur de la nature islandaise. Explorez les environs, des montagnes aux sources chaudes, et laissez-vous imprégner par l'atmosphère unique de l'Islande.", "Chez Booqueen, nous vous promettons un voyage vers Akureyri qui allie commodité, accessibilité et une immersion totale dans la beauté naturelle islandaise. Réservez votre vol dès maintenant et préparez-vous à vivre des moments magiques dans la perle du Nord."),
(200.00, "Système-Solaire", "Jupiter", "La géante gazeuse", "images/Système-Solaire/jupiter1.jpg", "images/Système-Solaire/jupiter2.jpg", "Bienvenue sur Jupiter, la plus grande planète de notre système solaire, une géante gazeuse aux tourbillons mystérieux et aux tempêtes tumultueuses. Chez Booqueen, nous vous invitons à explorer les secrets de cette planète majestueuse.", "Jupiter, avec son atmosphère dense et ses lunes fascinantes, offre une expérience captivante. Découvrez les tempêtes gigantesques, les bandes colorées et laissez-vous émerveiller par la grandeur de cette planète.", "Chez Booqueen, nous vous promettons un voyage spatial inoubliable. Profitez de nos vols confortables, de tarifs compétitifs et d'un service personnalisé pour votre voyage vers Jupiter."),
(180.00, "Système-Solaire", "Neptune", "La mystérieuse géante glacée", "images/Système-Solaire/neptune1.jpg", "images/Système-Solaire/neptune2.jpg", "Bienvenue sur Neptune, la mystérieuse géante glacée du système solaire, où des vents violents soufflent à travers son atmosphère bleue. Chez Booqueen, plongez-vous dans l'exploration de cette planète lointaine et fascinante.", "Neptune, avec ses anneaux délicats et ses lunes énigmatiques, offre un spectacle céleste captivant. Découvrez les secrets de cette planète glacée, où l'obscurité de l'espace contraste avec la beauté hypnotique de Neptune.", "Chez Booqueen, nous vous offrons une expérience spatiale unique. Embarquez pour un voyage vers Neptune avec nos vols spatiaux de pointe, des tarifs compétitifs et un service personnalisé pour une aventure interstellaire inoubliable."),
(170.00, "Système-Solaire", "Mars", "La planète rouge", "images/Système-Solaire/mars1.jpg", "images/Système-Solaire/mars2.jpg", "Bienvenue sur Mars, la fascinante planète rouge, symbole de l'exploration planétaire humaine. Chez Booqueen, plongez-vous dans les mystères de cette planète, connue pour ses déserts martiens et ses montagnes majestueuses.", "Mars, avec ses canyons profonds et ses calottes polaires, offre un terrain d'exploration unique. Découvrez les rovers qui parcourent la surface de Mars et imaginez-vous marchant sur cette planète rouge au cours de notre aventure spatiale.", "Chez Booqueen, nous vous invitons à vivre l'exploration de Mars avec nos vols spatiaux exceptionnels, des tarifs compétitifs et un service personnalisé pour une aventure cosmique inoubliable."),
(190.00, "Système-Solaire", "Saturne", "L'élégante aux anneaux", "images/Système-Solaire/saturne1.jpg", "images/Système-Solaire/saturne2.jpg", "Bienvenue sur Saturne, la magnifique géante aux anneaux, une planète célèbre pour sa beauté spectaculaire. Chez Booqueen, explorez l'élégance de cette planète, où des anneaux majestueux encerclent son atmosphère dorée.", "Saturne, avec ses lunes fascinantes et ses tempêtes tourbillonnantes, offre une expérience unique. Découvrez ses anneaux splendides et admirez la beauté de ses paysages célestes.", "Chez Booqueen, nous vous promettons un voyage exceptionnel vers Saturne. Profitez de vols confortables, de tarifs compétitifs et d'un service personnalisé pour une exploration inoubliable de cette planète fascinante.");